[tool.poetry]
name = "wub-hub"
version = "0.1.0"
description = ""
authors = ["Filipe Oliveira <hi@fmoliveira.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
